// Code generated by MockGen. DO NOT EDIT.
// Source: ./cloud_client.go

// Package cloudclientmocks is a generated GoMock package.
package cloudclientmocks

import (
	reflect "reflect"

	gomock "github.com/golang/mock/gomock"
	cloudclient "github.com/otterize/network-mapper/src/mapper/pkg/cloudclient"
)

// MockCloudClient is a mock of CloudClient interface.
type MockCloudClient struct {
	ctrl     *gomock.Controller
	recorder *MockCloudClientMockRecorder
}

// MockCloudClientMockRecorder is the mock recorder for MockCloudClient.
type MockCloudClientMockRecorder struct {
	mock *MockCloudClient
}

// NewMockCloudClient creates a new mock instance.
func NewMockCloudClient(ctrl *gomock.Controller) *MockCloudClient {
	mock := &MockCloudClient{ctrl: ctrl}
	mock.recorder = &MockCloudClientMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockCloudClient) EXPECT() *MockCloudClientMockRecorder {
	return m.recorder
}

// ReportDiscoveredIntents mocks base method.
func (m *MockCloudClient) ReportDiscoveredIntents(intents []cloudclient.IntentInput) bool {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ReportDiscoveredIntents", intents)
	ret0, _ := ret[0].(bool)
	return ret0
}

// ReportDiscoveredIntents indicates an expected call of ReportDiscoveredIntents.
func (mr *MockCloudClientMockRecorder) ReportDiscoveredIntents(intents interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ReportDiscoveredIntents", reflect.TypeOf((*MockCloudClient)(nil).ReportDiscoveredIntents), intents)
}
