// Code generated by github.com/Khan/genqlient, DO NOT EDIT.

package cloudclient

import (
	"context"

	"github.com/Khan/genqlient/graphql"
)

type HTTPConfigInput struct {
	Path   string     `json:"path"`
	Method HTTPMethod `json:"method"`
}

// GetPath returns HTTPConfigInput.Path, and is useful for accessing the field via an interface.
func (v *HTTPConfigInput) GetPath() string { return v.Path }

// GetMethod returns HTTPConfigInput.Method, and is useful for accessing the field via an interface.
func (v *HTTPConfigInput) GetMethod() HTTPMethod { return v.Method }

type HTTPMethod string

const (
	HTTPMethodGet     HTTPMethod = "GET"
	HTTPMethodPost    HTTPMethod = "POST"
	HTTPMethodPut     HTTPMethod = "PUT"
	HTTPMethodDelete  HTTPMethod = "DELETE"
	HTTPMethodOptions HTTPMethod = "OPTIONS"
	HTTPMethodTrace   HTTPMethod = "TRACE"
	HTTPMethodPatch   HTTPMethod = "PATCH"
	HTTPMethodConnect HTTPMethod = "CONNECT"
)

type IntentBody struct {
	Type      IntentType         `json:"type"`
	Topics    []KafkaConfigInput `json:"topics"`
	Resources []HTTPConfigInput  `json:"resources"`
}

// GetType returns IntentBody.Type, and is useful for accessing the field via an interface.
func (v *IntentBody) GetType() IntentType { return v.Type }

// GetTopics returns IntentBody.Topics, and is useful for accessing the field via an interface.
func (v *IntentBody) GetTopics() []KafkaConfigInput { return v.Topics }

// GetResources returns IntentBody.Resources, and is useful for accessing the field via an interface.
func (v *IntentBody) GetResources() []HTTPConfigInput { return v.Resources }

type IntentInput struct {
	Client string     `json:"client"`
	Server string     `json:"server"`
	Body   IntentBody `json:"body"`
}

// GetClient returns IntentInput.Client, and is useful for accessing the field via an interface.
func (v *IntentInput) GetClient() string { return v.Client }

// GetServer returns IntentInput.Server, and is useful for accessing the field via an interface.
func (v *IntentInput) GetServer() string { return v.Server }

// GetBody returns IntentInput.Body, and is useful for accessing the field via an interface.
func (v *IntentInput) GetBody() IntentBody { return v.Body }

type IntentType string

const (
	IntentTypeHttp  IntentType = "HTTP"
	IntentTypeKafka IntentType = "Kafka"
	IntentTypeGrpc  IntentType = "gRPC"
	IntentTypeRedis IntentType = "Redis"
)

type KafkaConfigInput struct {
	Topic     string         `json:"topic"`
	Operation KafkaOperation `json:"operation"`
}

// GetTopic returns KafkaConfigInput.Topic, and is useful for accessing the field via an interface.
func (v *KafkaConfigInput) GetTopic() string { return v.Topic }

// GetOperation returns KafkaConfigInput.Operation, and is useful for accessing the field via an interface.
func (v *KafkaConfigInput) GetOperation() KafkaOperation { return v.Operation }

type KafkaOperation string

const (
	KafkaOperationConsume         KafkaOperation = "consume"
	KafkaOperationProduce         KafkaOperation = "produce"
	KafkaOperationCreate          KafkaOperation = "create"
	KafkaOperationAlter           KafkaOperation = "alter"
	KafkaOperationDelete          KafkaOperation = "delete"
	KafkaOperationDescribe        KafkaOperation = "describe"
	KafkaOperationClusteraction   KafkaOperation = "ClusterAction"
	KafkaOperationDescribeconfigs KafkaOperation = "DescribeConfigs"
	KafkaOperationAlterconfigs    KafkaOperation = "AlterConfigs"
	KafkaOperationIdempotentwrite KafkaOperation = "IdempotentWrite"
)

// ReportDiscoveredSourcedIntentsResponse is returned by ReportDiscoveredSourcedIntents on success.
type ReportDiscoveredSourcedIntentsResponse struct {
	ReportDiscoveredSourcedIntents bool `json:"reportDiscoveredSourcedIntents"`
}

// GetReportDiscoveredSourcedIntents returns ReportDiscoveredSourcedIntentsResponse.ReportDiscoveredSourcedIntents, and is useful for accessing the field via an interface.
func (v *ReportDiscoveredSourcedIntentsResponse) GetReportDiscoveredSourcedIntents() bool {
	return v.ReportDiscoveredSourcedIntents
}

// __ReportDiscoveredSourcedIntentsInput is used internally by genqlient
type __ReportDiscoveredSourcedIntentsInput struct {
	Environment string        `json:"environment"`
	Source      string        `json:"source"`
	Intents     []IntentInput `json:"intents"`
}

// GetEnvironment returns __ReportDiscoveredSourcedIntentsInput.Environment, and is useful for accessing the field via an interface.
func (v *__ReportDiscoveredSourcedIntentsInput) GetEnvironment() string { return v.Environment }

// GetSource returns __ReportDiscoveredSourcedIntentsInput.Source, and is useful for accessing the field via an interface.
func (v *__ReportDiscoveredSourcedIntentsInput) GetSource() string { return v.Source }

// GetIntents returns __ReportDiscoveredSourcedIntentsInput.Intents, and is useful for accessing the field via an interface.
func (v *__ReportDiscoveredSourcedIntentsInput) GetIntents() []IntentInput { return v.Intents }

func ReportDiscoveredSourcedIntents(
	ctx context.Context,
	client graphql.Client,
	environment string,
	source string,
	intents []IntentInput,
) (*ReportDiscoveredSourcedIntentsResponse, error) {
	req := &graphql.Request{
		OpName: "ReportDiscoveredSourcedIntents",
		Query: `
mutation ReportDiscoveredSourcedIntents ($environment: ID!, $source: String!, $intents: [IntentInput!]!) {
	reportDiscoveredSourcedIntents(environment: $environment, source: $source, intents: $intents)
}
`,
		Variables: &__ReportDiscoveredSourcedIntentsInput{
			Environment: environment,
			Source:      source,
			Intents:     intents,
		},
	}
	var err error

	var data ReportDiscoveredSourcedIntentsResponse
	resp := &graphql.Response{Data: &data}

	err = client.MakeRequest(
		ctx,
		req,
		resp,
	)

	return &data, err
}
