// Code generated by github.com/Khan/genqlient, DO NOT EDIT.

package mapperclient

import (
	"context"
	"time"

	"github.com/Khan/genqlient/graphql"
)

type IstioConnection struct {
	SrcWorkload          string    `json:"srcWorkload"`
	SrcWorkloadNamespace string    `json:"srcWorkloadNamespace"`
	DstWorkload          string    `json:"dstWorkload"`
	DstWorkloadNamespace string    `json:"dstWorkloadNamespace"`
	RequestPaths         []string  `json:"requestPaths"`
	LastSeen             time.Time `json:"lastSeen"`
}

// GetSrcWorkload returns IstioConnection.SrcWorkload, and is useful for accessing the field via an interface.
func (v *IstioConnection) GetSrcWorkload() string { return v.SrcWorkload }

// GetSrcWorkloadNamespace returns IstioConnection.SrcWorkloadNamespace, and is useful for accessing the field via an interface.
func (v *IstioConnection) GetSrcWorkloadNamespace() string { return v.SrcWorkloadNamespace }

// GetDstWorkload returns IstioConnection.DstWorkload, and is useful for accessing the field via an interface.
func (v *IstioConnection) GetDstWorkload() string { return v.DstWorkload }

// GetDstWorkloadNamespace returns IstioConnection.DstWorkloadNamespace, and is useful for accessing the field via an interface.
func (v *IstioConnection) GetDstWorkloadNamespace() string { return v.DstWorkloadNamespace }

// GetRequestPaths returns IstioConnection.RequestPaths, and is useful for accessing the field via an interface.
func (v *IstioConnection) GetRequestPaths() []string { return v.RequestPaths }

// GetLastSeen returns IstioConnection.LastSeen, and is useful for accessing the field via an interface.
func (v *IstioConnection) GetLastSeen() time.Time { return v.LastSeen }

type IstioConnectionResults struct {
	Results []IstioConnection `json:"results"`
}

// GetResults returns IstioConnectionResults.Results, and is useful for accessing the field via an interface.
func (v *IstioConnectionResults) GetResults() []IstioConnection { return v.Results }

// __reportIstioConnectionsInput is used internally by genqlient
type __reportIstioConnectionsInput struct {
	Results IstioConnectionResults `json:"results"`
}

// GetResults returns __reportIstioConnectionsInput.Results, and is useful for accessing the field via an interface.
func (v *__reportIstioConnectionsInput) GetResults() IstioConnectionResults { return v.Results }

// reportIstioConnectionsResponse is returned by reportIstioConnections on success.
type reportIstioConnectionsResponse struct {
	ReportIstioConnectionResults bool `json:"reportIstioConnectionResults"`
}

// GetReportIstioConnectionResults returns reportIstioConnectionsResponse.ReportIstioConnectionResults, and is useful for accessing the field via an interface.
func (v *reportIstioConnectionsResponse) GetReportIstioConnectionResults() bool {
	return v.ReportIstioConnectionResults
}

func reportIstioConnections(
	ctx context.Context,
	client graphql.Client,
	results IstioConnectionResults,
) (*reportIstioConnectionsResponse, error) {
	req := &graphql.Request{
		OpName: "reportIstioConnections",
		Query: `
mutation reportIstioConnections ($results: IstioConnectionResults!) {
	reportIstioConnectionResults(results: $results)
}
`,
		Variables: &__reportIstioConnectionsInput{
			Results: results,
		},
	}
	var err error

	var data reportIstioConnectionsResponse
	resp := &graphql.Response{Data: &data}

	err = client.MakeRequest(
		ctx,
		req,
		resp,
	)

	return &data, err
}
