// Code generated by MockGen. DO NOT EDIT.
// Source: watcher.go

// Package mock_istiowatcher is a generated GoMock package.
package mock_istiowatcher

import (
	context "context"
	reflect "reflect"

	gomock "github.com/golang/mock/gomock"
	model "github.com/otterize/network-mapper/src/mapper/pkg/graph/model"
)

// MockIstioReporter is a mock of IstioReporter interface.
type MockIstioReporter struct {
	ctrl     *gomock.Controller
	recorder *MockIstioReporterMockRecorder
}

// MockIstioReporterMockRecorder is the mock recorder for MockIstioReporter.
type MockIstioReporterMockRecorder struct {
	mock *MockIstioReporter
}

// NewMockIstioReporter creates a new mock instance.
func NewMockIstioReporter(ctrl *gomock.Controller) *MockIstioReporter {
	mock := &MockIstioReporter{ctrl: ctrl}
	mock.recorder = &MockIstioReporterMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockIstioReporter) EXPECT() *MockIstioReporterMockRecorder {
	return m.recorder
}

// ReportIstioConnectionResults mocks base method.
func (m *MockIstioReporter) ReportIstioConnectionResults(ctx context.Context, results model.IstioConnectionResults) (bool, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ReportIstioConnectionResults", ctx, results)
	ret0, _ := ret[0].(bool)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// ReportIstioConnectionResults indicates an expected call of ReportIstioConnectionResults.
func (mr *MockIstioReporterMockRecorder) ReportIstioConnectionResults(ctx, results interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ReportIstioConnectionResults", reflect.TypeOf((*MockIstioReporter)(nil).ReportIstioConnectionResults), ctx, results)
}
