// Code generated by MockGen. DO NOT EDIT.
// Source: client.go

// Package mock_mapperclient is a generated GoMock package.
package mock_mapperclient

import (
	context "context"
	reflect "reflect"

	gomock "github.com/golang/mock/gomock"
	mapperclient "github.com/otterize/network-mapper/src/exp/istio-watcher/mapperclient"
)

// MockMapperClient is a mock of MapperClient interface.
type MockMapperClient struct {
	ctrl     *gomock.Controller
	recorder *MockMapperClientMockRecorder
}

// MockMapperClientMockRecorder is the mock recorder for MockMapperClient.
type MockMapperClientMockRecorder struct {
	mock *MockMapperClient
}

// NewMockMapperClient creates a new mock instance.
func NewMockMapperClient(ctrl *gomock.Controller) *MockMapperClient {
	mock := &MockMapperClient{ctrl: ctrl}
	mock.recorder = &MockMapperClientMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockMapperClient) EXPECT() *MockMapperClientMockRecorder {
	return m.recorder
}

// ReportIstioConnections mocks base method.
func (m *MockMapperClient) ReportIstioConnections(ctx context.Context, results mapperclient.IstioConnectionResults) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ReportIstioConnections", ctx, results)
	ret0, _ := ret[0].(error)
	return ret0
}

// ReportIstioConnections indicates an expected call of ReportIstioConnections.
func (mr *MockMapperClientMockRecorder) ReportIstioConnections(ctx, results interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ReportIstioConnections", reflect.TypeOf((*MockMapperClient)(nil).ReportIstioConnections), ctx, results)
}
