// Code generated by github.com/Khan/genqlient, DO NOT EDIT.

package mapperclient

import (
	"context"

	"github.com/Khan/genqlient/graphql"
)

// FormattedCRDsResponse is returned by FormattedCRDs on success.
type FormattedCRDsResponse struct {
	FormattedCRDs string `json:"formattedCRDs"`
}

// GetFormattedCRDs returns FormattedCRDsResponse.FormattedCRDs, and is useful for accessing the field via an interface.
func (v *FormattedCRDsResponse) GetFormattedCRDs() string { return v.FormattedCRDs }

// ServiceIntentsResponse is returned by ServiceIntents on success.
type ServiceIntentsResponse struct {
	ServiceIntents []ServiceIntentsServiceIntents `json:"serviceIntents"`
}

// GetServiceIntents returns ServiceIntentsResponse.ServiceIntents, and is useful for accessing the field via an interface.
func (v *ServiceIntentsResponse) GetServiceIntents() []ServiceIntentsServiceIntents {
	return v.ServiceIntents
}

// ServiceIntentsServiceIntents includes the requested fields of the GraphQL type ServiceIntents.
type ServiceIntentsServiceIntents struct {
	Name    string                                               `json:"name"`
	Intents []ServiceIntentsServiceIntentsIntentsServiceIdentity `json:"intents"`
}

// GetName returns ServiceIntentsServiceIntents.Name, and is useful for accessing the field via an interface.
func (v *ServiceIntentsServiceIntents) GetName() string { return v.Name }

// GetIntents returns ServiceIntentsServiceIntents.Intents, and is useful for accessing the field via an interface.
func (v *ServiceIntentsServiceIntents) GetIntents() []ServiceIntentsServiceIntentsIntentsServiceIdentity {
	return v.Intents
}

// ServiceIntentsServiceIntentsIntentsServiceIdentity includes the requested fields of the GraphQL type ServiceIdentity.
type ServiceIntentsServiceIntentsIntentsServiceIdentity struct {
	Name      string `json:"name"`
	Namespace string `json:"namespace"`
}

// GetName returns ServiceIntentsServiceIntentsIntentsServiceIdentity.Name, and is useful for accessing the field via an interface.
func (v *ServiceIntentsServiceIntentsIntentsServiceIdentity) GetName() string { return v.Name }

// GetNamespace returns ServiceIntentsServiceIntentsIntentsServiceIdentity.Namespace, and is useful for accessing the field via an interface.
func (v *ServiceIntentsServiceIntentsIntentsServiceIdentity) GetNamespace() string {
	return v.Namespace
}

func FormattedCRDs(
	ctx context.Context,
	client graphql.Client,
) (*FormattedCRDsResponse, error) {
	req := &graphql.Request{
		OpName: "FormattedCRDs",
		Query: `
query FormattedCRDs {
	formattedCRDs
}
`,
	}
	var err error

	var data FormattedCRDsResponse
	resp := &graphql.Response{Data: &data}

	err = client.MakeRequest(
		ctx,
		req,
		resp,
	)

	return &data, err
}

func ServiceIntents(
	ctx context.Context,
	client graphql.Client,
) (*ServiceIntentsResponse, error) {
	req := &graphql.Request{
		OpName: "ServiceIntents",
		Query: `
query ServiceIntents {
	serviceIntents {
		name
		intents {
			name
			namespace
		}
	}
}
`,
	}
	var err error

	var data ServiceIntentsResponse
	resp := &graphql.Response{Data: &data}

	err = client.MakeRequest(
		ctx,
		req,
		resp,
	)

	return &data, err
}
