// Code generated by github.com/Khan/genqlient, DO NOT EDIT.

package client

import (
	"context"

	"github.com/Khan/genqlient/graphql"
)

type CaptureResultForSrcIp struct {
	SrcIp        string   `json:"srcIp"`
	Destinations []string `json:"destinations"`
}

// GetSrcIp returns CaptureResultForSrcIp.SrcIp, and is useful for accessing the field via an interface.
func (v *CaptureResultForSrcIp) GetSrcIp() string { return v.SrcIp }

// GetDestinations returns CaptureResultForSrcIp.Destinations, and is useful for accessing the field via an interface.
func (v *CaptureResultForSrcIp) GetDestinations() []string { return v.Destinations }

type CaptureResults struct {
	Results []CaptureResultForSrcIp `json:"results"`
}

// GetResults returns CaptureResults.Results, and is useful for accessing the field via an interface.
func (v *CaptureResults) GetResults() []CaptureResultForSrcIp { return v.Results }

type SocketScanResultForSrcIp struct {
	SrcIp   string   `json:"srcIp"`
	DestIps []string `json:"destIps"`
}

// GetSrcIp returns SocketScanResultForSrcIp.SrcIp, and is useful for accessing the field via an interface.
func (v *SocketScanResultForSrcIp) GetSrcIp() string { return v.SrcIp }

// GetDestIps returns SocketScanResultForSrcIp.DestIps, and is useful for accessing the field via an interface.
func (v *SocketScanResultForSrcIp) GetDestIps() []string { return v.DestIps }

type SocketScanResults struct {
	Results []SocketScanResultForSrcIp `json:"results"`
}

// GetResults returns SocketScanResults.Results, and is useful for accessing the field via an interface.
func (v *SocketScanResults) GetResults() []SocketScanResultForSrcIp { return v.Results }

// __reportCaptureResultsInput is used internally by genqlient
type __reportCaptureResultsInput struct {
	Results CaptureResults `json:"results"`
}

// GetResults returns __reportCaptureResultsInput.Results, and is useful for accessing the field via an interface.
func (v *__reportCaptureResultsInput) GetResults() CaptureResults { return v.Results }

// __reportSocketScanResultsInput is used internally by genqlient
type __reportSocketScanResultsInput struct {
	Results SocketScanResults `json:"results"`
}

// GetResults returns __reportSocketScanResultsInput.Results, and is useful for accessing the field via an interface.
func (v *__reportSocketScanResultsInput) GetResults() SocketScanResults { return v.Results }

// reportCaptureResultsResponse is returned by reportCaptureResults on success.
type reportCaptureResultsResponse struct {
	ReportCaptureResults bool `json:"reportCaptureResults"`
}

// GetReportCaptureResults returns reportCaptureResultsResponse.ReportCaptureResults, and is useful for accessing the field via an interface.
func (v *reportCaptureResultsResponse) GetReportCaptureResults() bool { return v.ReportCaptureResults }

// reportSocketScanResultsResponse is returned by reportSocketScanResults on success.
type reportSocketScanResultsResponse struct {
	ReportSocketScanResults bool `json:"reportSocketScanResults"`
}

// GetReportSocketScanResults returns reportSocketScanResultsResponse.ReportSocketScanResults, and is useful for accessing the field via an interface.
func (v *reportSocketScanResultsResponse) GetReportSocketScanResults() bool {
	return v.ReportSocketScanResults
}

func reportCaptureResults(
	ctx context.Context,
	client graphql.Client,
	results CaptureResults,
) (*reportCaptureResultsResponse, error) {
	req := &graphql.Request{
		OpName: "reportCaptureResults",
		Query: `
mutation reportCaptureResults ($results: CaptureResults!) {
	reportCaptureResults(results: $results)
}
`,
		Variables: &__reportCaptureResultsInput{
			Results: results,
		},
	}
	var err error

	var data reportCaptureResultsResponse
	resp := &graphql.Response{Data: &data}

	err = client.MakeRequest(
		ctx,
		req,
		resp,
	)

	return &data, err
}

func reportSocketScanResults(
	ctx context.Context,
	client graphql.Client,
	results SocketScanResults,
) (*reportSocketScanResultsResponse, error) {
	req := &graphql.Request{
		OpName: "reportSocketScanResults",
		Query: `
mutation reportSocketScanResults ($results: SocketScanResults!) {
	reportSocketScanResults(results: $results)
}
`,
		Variables: &__reportSocketScanResultsInput{
			Results: results,
		},
	}
	var err error

	var data reportSocketScanResultsResponse
	resp := &graphql.Response{Data: &data}

	err = client.MakeRequest(
		ctx,
		req,
		resp,
	)

	return &data, err
}
