// Code generated by github.com/99designs/gqlgen, DO NOT EDIT.

package model

import (
	"time"
)

type CaptureResultForSrcIP struct {
	SrcIP        string        `json:"srcIp"`
	Destinations []Destination `json:"destinations"`
}

type CaptureResults struct {
	Results []CaptureResultForSrcIP `json:"results"`
}

type Destination struct {
	Destination string    `json:"destination"`
	LastSeen    time.Time `json:"lastSeen"`
}

type OtterizeServiceIdentity struct {
	Name      string `json:"name"`
	Namespace string `json:"namespace"`
}

type ServiceIntents struct {
	Client  *OtterizeServiceIdentity  `json:"client"`
	Intents []OtterizeServiceIdentity `json:"intents"`
}

type SocketScanResultForSrcIP struct {
	SrcIP   string        `json:"srcIp"`
	DestIps []Destination `json:"destIps"`
}

type SocketScanResults struct {
	Results []SocketScanResultForSrcIP `json:"results"`
}
