// Code generated by github.com/99designs/gqlgen, DO NOT EDIT.

package model

type CaptureResultForSrcIP struct {
	SrcIP        string   `json:"srcIp"`
	Destinations []string `json:"destinations"`
}

type CaptureResults struct {
	Results []CaptureResultForSrcIP `json:"results"`
}

type ServiceIntents struct {
	Name    string   `json:"name"`
	Intents []string `json:"intents"`
}
