// Code generated by github.com/99designs/gqlgen, DO NOT EDIT.

package model

type CaptureResultForSrcIP struct {
	SrcIP        string   `json:"srcIp"`
	Destinations []string `json:"destinations"`
}

type CaptureResults struct {
	Results []CaptureResultForSrcIP `json:"results"`
}

type OtterizeServiceIdentity struct {
	Name      string `json:"name"`
	Namespace string `json:"namespace"`
}

type ServiceIntents struct {
	Name    string                    `json:"name"`
	Intents []OtterizeServiceIdentity `json:"intents"`
}

type SocketScanResultForSrcIP struct {
	SrcIP   string   `json:"srcIp"`
	DestIps []string `json:"destIps"`
}

type SocketScanResults struct {
	Results []SocketScanResultForSrcIP `json:"results"`
}
