// Code generated by github.com/Khan/genqlient, DO NOT EDIT.

package mapperclient

import (
	"context"
	"time"

	"github.com/Khan/genqlient/graphql"
)

type CaptureResultForSrcIp struct {
	Src          OtterizeServiceIdentityInput `json:"src"`
	Destinations []Destination                `json:"destinations"`
}

// GetSrc returns CaptureResultForSrcIp.Src, and is useful for accessing the field via an interface.
func (v *CaptureResultForSrcIp) GetSrc() OtterizeServiceIdentityInput { return v.Src }

// GetDestinations returns CaptureResultForSrcIp.Destinations, and is useful for accessing the field via an interface.
func (v *CaptureResultForSrcIp) GetDestinations() []Destination { return v.Destinations }

type CaptureResults struct {
	Results []CaptureResultForSrcIp `json:"results"`
}

// GetResults returns CaptureResults.Results, and is useful for accessing the field via an interface.
func (v *CaptureResults) GetResults() []CaptureResultForSrcIp { return v.Results }

type Destination struct {
	Destination OtterizeServiceIdentityInput `json:"destination"`
	LastSeen    time.Time                    `json:"lastSeen"`
}

// GetDestination returns Destination.Destination, and is useful for accessing the field via an interface.
func (v *Destination) GetDestination() OtterizeServiceIdentityInput { return v.Destination }

// GetLastSeen returns Destination.LastSeen, and is useful for accessing the field via an interface.
func (v *Destination) GetLastSeen() time.Time { return v.LastSeen }

type OtterizeServiceIdentityInput struct {
	Name      string `json:"name"`
	Namespace string `json:"namespace"`
}

// GetName returns OtterizeServiceIdentityInput.Name, and is useful for accessing the field via an interface.
func (v *OtterizeServiceIdentityInput) GetName() string { return v.Name }

// GetNamespace returns OtterizeServiceIdentityInput.Namespace, and is useful for accessing the field via an interface.
func (v *OtterizeServiceIdentityInput) GetNamespace() string { return v.Namespace }

type SocketScanResultForSrcIp struct {
	Src          OtterizeServiceIdentityInput `json:"src"`
	Destinations []Destination                `json:"destinations"`
}

// GetSrc returns SocketScanResultForSrcIp.Src, and is useful for accessing the field via an interface.
func (v *SocketScanResultForSrcIp) GetSrc() OtterizeServiceIdentityInput { return v.Src }

// GetDestinations returns SocketScanResultForSrcIp.Destinations, and is useful for accessing the field via an interface.
func (v *SocketScanResultForSrcIp) GetDestinations() []Destination { return v.Destinations }

type SocketScanResults struct {
	Results []SocketScanResultForSrcIp `json:"results"`
}

// GetResults returns SocketScanResults.Results, and is useful for accessing the field via an interface.
func (v *SocketScanResults) GetResults() []SocketScanResultForSrcIp { return v.Results }

// __reportCaptureResultsInput is used internally by genqlient
type __reportCaptureResultsInput struct {
	Results CaptureResults `json:"results"`
}

// GetResults returns __reportCaptureResultsInput.Results, and is useful for accessing the field via an interface.
func (v *__reportCaptureResultsInput) GetResults() CaptureResults { return v.Results }

// __reportSocketScanResultsInput is used internally by genqlient
type __reportSocketScanResultsInput struct {
	Results SocketScanResults `json:"results"`
}

// GetResults returns __reportSocketScanResultsInput.Results, and is useful for accessing the field via an interface.
func (v *__reportSocketScanResultsInput) GetResults() SocketScanResults { return v.Results }

// reportCaptureResultsResponse is returned by reportCaptureResults on success.
type reportCaptureResultsResponse struct {
	ReportCaptureResults bool `json:"reportCaptureResults"`
}

// GetReportCaptureResults returns reportCaptureResultsResponse.ReportCaptureResults, and is useful for accessing the field via an interface.
func (v *reportCaptureResultsResponse) GetReportCaptureResults() bool { return v.ReportCaptureResults }

// reportSocketScanResultsResponse is returned by reportSocketScanResults on success.
type reportSocketScanResultsResponse struct {
	ReportSocketScanResults bool `json:"reportSocketScanResults"`
}

// GetReportSocketScanResults returns reportSocketScanResultsResponse.ReportSocketScanResults, and is useful for accessing the field via an interface.
func (v *reportSocketScanResultsResponse) GetReportSocketScanResults() bool {
	return v.ReportSocketScanResults
}

func reportCaptureResults(
	ctx context.Context,
	client graphql.Client,
	results CaptureResults,
) (*reportCaptureResultsResponse, error) {
	req := &graphql.Request{
		OpName: "reportCaptureResults",
		Query: `
mutation reportCaptureResults ($results: CaptureResults!) {
	reportCaptureResults(results: $results)
}
`,
		Variables: &__reportCaptureResultsInput{
			Results: results,
		},
	}
	var err error

	var data reportCaptureResultsResponse
	resp := &graphql.Response{Data: &data}

	err = client.MakeRequest(
		ctx,
		req,
		resp,
	)

	return &data, err
}

func reportSocketScanResults(
	ctx context.Context,
	client graphql.Client,
	results SocketScanResults,
) (*reportSocketScanResultsResponse, error) {
	req := &graphql.Request{
		OpName: "reportSocketScanResults",
		Query: `
mutation reportSocketScanResults ($results: SocketScanResults!) {
	reportSocketScanResults(results: $results)
}
`,
		Variables: &__reportSocketScanResultsInput{
			Results: results,
		},
	}
	var err error

	var data reportSocketScanResultsResponse
	resp := &graphql.Response{Data: &data}

	err = client.MakeRequest(
		ctx,
		req,
		resp,
	)

	return &data, err
}
