name: e2e tests
on:
  workflow_call:
    inputs:
      registry:
        required: true
        type: string
      mapper-image:
        required: true
        type: string
      sniffer-image:
        required: true
        type: string
      mapper-tag:
        required: true
        type: string
      sniffer-tag:
        required: true
        type: string

jobs:
  e2e-tests:
    timeout-minutes: 5
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Set up Helm
        uses: azure/setup-helm@v3

      - name: Start minikube
        uses: medyagh/setup-minikube@master

      - name: Deploy Otterize
        run: |-
          helm repo add otterize https://helm.otterize.com
          helm repo update
          helm install otterize otterize/network-mapper -n otterize-system --create-namespace --wait

#      - uses: actions/setup-node@v3
#        with:
#          node-version: 18
#
#      - name: Install dependencies
#        run: |
#          cd src/frontend
#          npm ci
#          npm install playwright-chromium
#
#      - name: Run e2e tests
#        env:
#          BASE_URL: ${{ inputs.app-url }}
#        run: |
#          cd src/frontend
#          npm run test:e2e:run
#
#      - uses: actions/upload-artifact@v3
#        if: always()
#        with:
#          name: playwright-report
#          path: src/frontend/playwright-report
#          retention-days: 30